variables:
  BuildConfiguration: 'Release'
  CI: true
  PNPM_VERSION: 7.26.0
  NODE_VERSION: 16.14.2
  DOTNET_VERSION: 6.0.x

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: 'Frontend'
    pool:
      vmImage: 'ubuntu-20.04'
      demands: azureps

    steps:
      - task: NodeTool@0
        displayName: 'Install Node.js $(NODE_VERSION)'
        inputs:
          versionSpec: $(NODE_VERSION)

      - task: 'Bash@3'
        displayName: 'corepack enable'
        inputs:
          workingDir: '.'
          targetType: 'inline'
          script: 'corepack enable'

      - task: 'Bash@3'
        displayName: 'pnpm i'
        inputs:
          workingDir: '.'
          targetType: 'inline'
          script: 'pnpm i'

      - task: 'Bash@3'
        displayName: 'purge Gov.uk'
        inputs:
          workingDir: '.'
          targetType: 'inline'
          script: 'rm -rf src/GovUk.*'

      - task: 'Bash@3'
        displayName: 'pnpm install...'
        inputs:
          workingDir: '.'
          targetType: 'inline'
          script: 'pnpm --filter=explore-education-statistics-frontend... install'


      - task: 'Bash@3'
        displayName: 'build FE'
        inputs:
          workingDir: '.'
          targetType: 'inline'
          script: 'pnpm --filter=explore-education-statistics-frontend build'

      - task: 'Bash@3'
        displayName: 'prod install'
        inputs:
          workingDir: '.'
          targetType: 'inline'
          script: 'pnpm --filter=explore-education-statistics-frontend... --prod install'

      - task: 'ArchiveFiles@2'
        displayName: 'Archive frontend'
        inputs:
          rootFolderOrFile: './src/explore-education-statistics-frontend'
          includeRootFolder: false
          archiveFile: '$(Build.ArtifactStagingDirectory)/public-frontend.zip'

      - task: 'PublishPipelineArtifact@0'
        displayName: 'Publish Pipeline Artifact'
        inputs:
          artifactName: 'public-frontend'
          targetPath: '$(Build.ArtifactStagingDirectory)'
